# Project information
site_name: Disaster的提升之路
site_url: https://disaster1-tesk.github.ionote/
site_author: Disaster
site_description: 记录个人的成长历程

# Repository
repo_name: disaster1-tesknote
repo_url: https://github.com/disaster1-tesknote
edit_uri: https://github.com/disaster1-tesknote/tree/main/docs

# Copyright
copyright: Copyright &copy; 2023 Disaster

# Configuration
theme:
  name: material
  custom_dir: material/.overrides
  language: zh
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      # accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      # accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/logo.png
  logo: assets/images/logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline




# [Navigtion]
nav:
  - 百宝箱:
      - REDISSION:
        - redisson的中文文档: note/redission/redission-文档.md
      - JVM:
          - 第01章_JVM与Java体系结构: note/jvm/JVM系列-第1章-JVM与Java体系结构.md
          - 第02章_类加载子系统: note/jvm/JVM系列-第2章-类加载子系统.md
          - 第03章_运行时数据区: note/jvm/JVM系列-第3章-运行时数据区.md
          - 第04章_虚拟机栈: note/jvm/JVM系列-第4章-虚拟机栈.md
          - 第05章_堆: note/jvm/JVM系列-第5章-堆.md
          - 第06章_方法区: note/jvm/JVM系列-第6章-方法区.md
          - 第07章_对象的实例化内存布局与访问定位: note/jvm/JVM系列-第7章-对象的实例化内存布局与访问定位.md
          - 第08章_执行引擎: note/jvm/JVM系列-第8章-执行引擎.md
          - 第09章_StringTable(字符串常量池): note/jvm/JVM系列-第9章-StringTable(字符串常量池).md
          - 第10章_垃圾回收概述和相关算法: note/jvm/JVM系列-第10章-垃圾回收概述和相关算法.md
          - 第11章_垃圾回收相关概念: note/jvm/JVM系列-第11章-垃圾回收相关概念.md
          - 第12章_垃圾回收器: note/jvm/JVM系列-第12章-垃圾回收器.md
      - MYSQL:
        - 基础篇:
          - 第00章_写在前面: note/mysql/基础篇/第00章_写在前面.md
          - 第01章_数据库概述: note/mysql/基础篇/第01章_数据库概述.md
          - 第02章_MySQL环境搭建: note/mysql/基础篇/第02章_MySQL环境搭建.md
          - 第03章_基本的SELECT语句: note/mysql/基础篇/第03章_基本的SELECT语句.md
          - 第04章_运算符: note/mysql/基础篇/第04章_运算符.md
          - 第05章_排序与分页: note/mysql/基础篇/第05章_排序与分页.md
          - 第06章_多表查询: note/mysql/基础篇/第06章_多表查询.md
          - 第07章_单行函数: note/mysql/基础篇/第07章_单行函数.md
          - 第08章_聚合函数: note/mysql/基础篇/第08章_聚合函数.md
          - 第09章_子查询: note/mysql/基础篇/第09章_子查询.md
          - 第10章_创建和管理表: note/mysql/基础篇/第10章_创建和管理表.md
          - 第11章_数据处理之增删改: note/mysql/基础篇/第11章_数据处理之增删改.md
          - 第12章_MySQL数据类型精讲: note/mysql/基础篇/第12章_MySQL数据类型精讲.md
          - 第13章_约束: note/mysql/基础篇/第13章_约束.md
          - 第14章_视图: note/mysql/基础篇/第14章_视图.md
          - 第15章_存储过程与函数: note/mysql/基础篇/第15章_存储过程与函数.md
          - 第16章_变量、流程控制与游标: note/mysql/基础篇/第16章_变量、流程控制与游标.md
          - 第17章_触发器: note/mysql/基础篇/第17章_触发器.md
          - 第18章_MySQL8其它新特性: note/mysql/基础篇/第18章_MySQL8其它新特性.md
        - 高级篇:
          - 第01章 Linux下MySQL的安装与使用: note/mysql/高级篇/第01章 Linux下MySQL的安装与使用.md
          - 第02章 MySQL的数据目录: note/mysql/高级篇/第02章 MySQL的数据目录.md
          - 第03章 用户与权限管理: note/mysql/高级篇/第03章 用户与权限管理.md
          - 第04章 逻辑架构: note/mysql/高级篇/第04章 逻辑架构.md
          - 第05章 存储引擎: note/mysql/高级篇/第05章 存储引擎.md
          - 第06章 索引的数据结构: note/mysql/高级篇/第06章 索引的数据结构.md
          - 第07章 InnoDB数据存储结构: note/mysql/高级篇/第07章 InnoDB数据存储结构.md
          - 第08章 索引的创建与设计原则: note/mysql/高级篇/第08章 索引的创建与设计原则.md
          - 第09章 性能分析工具的使用: note/mysql/高级篇/第09章 性能分析工具的使用.md
          - 第10章 索引优化与查询优化: note/mysql/高级篇/第10章 索引优化与查询优化.md
          - 第11章 数据库的设计规范: note/mysql/高级篇/第11章 数据库的设计规范.md
          - 第12章 数据库其它调优策略: note/mysql/高级篇/第12章 数据库其它调优策略.md
          - 第13章 事务基础知识: note/mysql/高级篇/第13章 事务基础知识.md
          - 第14章 MySQL事务日志: note/mysql/高级篇/第14章 MySQL事务日志.md
          - 第15章 锁: note/mysql/高级篇/第15章 锁.md
          - 第16章 多版本并发控制: note/mysql/高级篇/第16章 多版本并发控制.md
          - 第17章 其它数据库日志: note/mysql/高级篇/第17章 其它数据库日志.md
          - 第18章 主从复制: note/mysql/高级篇/第18章 主从复制.md
          - 第19章 数据库备份与恢复: note/mysql/高级篇/第19章 数据库备份与恢复.md

      - 简历: resume/Java程序员简历模板.md
  - 博客:
      - 架构:
        - 微服务系列之单体架构: blog/microservice/微服务系列之单体架构.md
        - 微服务系列之初探“微服务架构”: blog/microservice/微服务系列之初探“微服务架构”.md
        - 微服务系列之微服务架构: blog/microservice/微服务系列之微服务架构.md
        - 微服务系列之远程服务调用: blog/microservice/微服务系列之远程服务调用.md
        - 微服务之异步消息通信: blog/microservice/微服务之异步消息通信.md
        - 微服务之事务处理: blog/microservice/微服务之事务处理.md
        - 微服务之服务容错: blog/microservice/微服务之服务容错.md
        - 微服务之流量控制: blog/microservice/微服务之流量控制.md
      - 设计模式:
          - 前言: blog/designmodel/前言.md
          - 23种设计模式: blog/designmodel/23种设计模式.md
  - LELTS:
      - English_level_up_tips:
        - 认知篇: lelts/part-1/1-understanding.md
        - 单词篇: lelts/part-1/2-vocabulary.md
        - 听力篇: lelts/part-1/3-listening.md
        - 阅读篇: lelts/part-1/4-reading.md
        - 口语篇: lelts/part-1/5-speaking.md
      - everyone-can-use-english:
        - 第一章：起点: lelts/everyone-can-us-english/chapter1.md
        - 第二章：口语: lelts/everyone-can-us-english/chapter2.md
        - 第三章：语音: lelts/everyone-can-us-english/chapter3.md
        - 第四章：朗读: lelts/everyone-can-us-english/chapter4.md
        - 第五章：词典: lelts/everyone-can-us-english/chapter5.md
        - 第六章：语法: lelts/everyone-can-us-english/chapter6.md
        - 第七章：精读: lelts/everyone-can-us-english/chapter7.md
        - 第八章：叮嘱: lelts/everyone-can-us-english/chapter8.md
        - 后记: everyone-can-us-english/end.md
      - TheCompleteTrainingManual:
          - TheCompleteTrainingManual: lelts/TheCompleteTrainingManual/TheCompleteTrainingManual.md
          - TheCompleteTrainingManual_pdf: lelts/TheCompleteTrainingManual/TheCompleteTrainingManual.pdf
  - talk skills:
      - 我也有话要说:
          - 千万别装: talkskill/ch01.md
          - 信任你的听众: talkskill/ch02.md
          - 听众到底要什么？: talkskill/ch03.md
          - 你我皆凡人: talkskill/ch04.md
          - 怎样开头？: talkskill/ch05.md
          - 你想干什么？: talkskill/ch06.md
          - 什么元素最重要？: talkskill/ch07.md
          - 一次只说一件事: talkskill/ch08.md
          - 你有 99%的可能性被误解: talkskill/ch09.md
          - 更可能是你自己没说清楚: talkskill/ch10.md
          - 使用你自己的语言: talkskill/ch11.md
          - 只说自己真正相信的话: talkskill/ch12.md
          - 不要指望听众能够自动与你感同身受: talkskill/ch13.md
          - 小心听众的情绪: talkskill/ch14.md
          - 做一个值得信赖的人: talkskill/ch15.md
          - 听众最关心什么？: talkskill/ch16.md
          - 听众喜欢什么样的人？: talkskill/ch17.md
          - 把一切证据都准备好: talkskill/ch18.md
          - 制造效果的利器——契诃夫之枪: talkskill/ch19.md
          - 制造效果的另外一个小技巧：重复: talkskill/ch20.md
          - 让语言生动起来并不难: talkskill/ch21.md
          - 新手最难掌握的重要技巧：停顿: talkskill/ch22.md
          - 最好的互动方式——让听众思考: talkskill/ch23.md
          - 向听众提问时要注意什么？: talkskill/ch24.md
          - 证明他人错误≠证明自己正确: talkskill/ch25.md
          - 为了学会讲，要先学会听: talkskill/ch26.md
          - 慎用名言警句（或其它陈词滥调）: talkskill/ch27.md
          - 只不过是换一种说法而已: talkskill/ch28.md
          - 记录听众的反应: talkskill/ch29.md
          - 要说清楚“是什么”更要说清楚“不是什么”: talkskill/ch30.md
          - 主角与配角: talkskill/ch31.md
          - 小心被辅助工具绑架: talkskill/ch32.md
          - 使用视觉辅助工具的第一原则：简单: talkskill/ch33.md
          - 控制自己的讲话范围: talkskill/ch34.md
          - 日常谈话是最好的练习机会: talkskill/ch35.md
          - 废话！废话？: talkskill/ch36.md
          - 成为能说那话的人: talkskill/ch37.md
          - 什么时候说结论: talkskill/ch38.md
          - 如何克服紧张？: talkskill/ch39.md
          - 何来激情？: talkskill/ch40.md
  - 个人杂谈:
      - 面试总结: note/whisper/chapter1.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#plugins:
#  - meta